{
 "title": "PV-Anlage",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Leistung/Batterie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Batterie",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "deye.battery.1.soc" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 1, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "deye.battery.1.soc" }
   ]
  },
  {
   "title": "PV",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "deye.dc.total.power" }
   ]
  },
  {
   "title": "Haus",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "deye.ac.ups.total.power" }
   ]
  },
  {
   "title": "Netz",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "deye.ac.total.power" }
   ]
  },
  {
   "title": "Hausstrom Anteile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "target": "alias(interpolate(removeBelowValue(deye.ac.total.power, 0), 6), 'Netz')"
    },
    {
     "target": "alias(interpolate(deye.dc.total.power, 6), 'PV')"
    },
    {
     "target": "alias(interpolate(removeBelowValue(deye.battery.1.power, 0), 6), 'Batterie')"
    },
    {
     "target": "alias(interpolate(deye.ac.ups.total.power, 6), 'Haus')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "deye.battery.1.power" }
   ]
  },
  {
   "title": "Batterie",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "${pLaden}/${count}  * ((${__to:date:seconds}-${__from:date:seconds})/3600)",
     "reducer": "sum",
     "type": "math"
    },
    {
     "expression": "${pEntladen}/${count} * ((${__to:date:seconds}-${__from:date:seconds})/3600)",
     "reducer": "sum",
     "type": "math"
    }
   ]
  },
  {
   "title": "PV",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "${p}/$count * ((${__to:date:seconds}-${__from:date:seconds})/3600)",
     "reducer": "sum",
     "type": "math"
    }
   ]
  },
  {
   "title": "Haus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "${p}/$count * ((${__to:date:seconds}-${__from:date:seconds})/3600)",
     "reducer": "sum",
     "type": "math"
    }
   ]
  },
  {
   "title": "Netz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "${pOut}/${count} * ((${__to:date:seconds}-${__from:date:seconds})/3600)",
     "reducer": "sum",
     "type": "math"
    },
    {
     "expression": "${pIn}/${count} * ((${__to:date:seconds}-${__from:date:seconds})/3600)",
     "reducer": "sum",
     "type": "math"
    }
   ]
  },
  {
   "title": "Leistungen",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "target": "alias(deye.ac.total.power, 'Netz (neg=Einspeisung, pos=Bezug)')"
    },
    {
     "target": "alias(deye.ac.ups.total.power, 'Hausbedarf')"
    },
    {
     "target": "alias(deye.dc.total.power, 'PV Anlage')"
    },
    {
     "target": "alias(deye.battery.1.power, 'Batterie (neg=Laden, pos=Entladen)')"
    },
    {
     "expression": "${PowerGrid}+${PowerPV}+${PowerBatterie} - ${PowerHouse}",
     "type": "math"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "target": "alias(deye.battery.1.current, 'Ladestrom (neg=Laden, pos=Entladen)')"
    },
    {
     "target": "alias(deye.battery.1.voltage, 'Spannung')"
    },
    {
     "target": "alias(deye.battery.1.soc, 'Füllstand')"
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "alias(deye.battery.1.temperature, 'Batterie Temperatur')"
    },
    {
     "target": "alias(deye.ac.temperature, 'Wechselrichter Temperatur ')"
    },
    {
     "target": "alias(deye.radiator.temp, 'Radiator Temperatur ')"
    }
   ]
  },
  { "title": "Haus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Leistung",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "target": "alias(deye.ac.ups.total.power, 'Total')"
    },
    {
     "target": "alias(deye.ac.ups.l1.power, 'L1')"
    },
    {
     "target": "alias(deye.ac.ups.l2.power, 'L2')"
    },
    {
     "target": "alias(deye.ac.ups.l3.power, 'L3')"
    }
   ]
  },
  {
   "title": "Spannung",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "target": "alias(deye.ac.ups.l1.voltage, 'L1')"
    },
    {
     "target": "alias(deye.ac.ups.l2.voltage, 'L2')"
    },
    {
     "target": "alias(deye.ac.ups.l3.voltage, 'L3')"
    }
   ]
  },
  {
   "title": "Strom",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "target": "alias(deye.ac.ups.l1.current, 'L1')"
    },
    {
     "target": "alias(deye.ac.ups.l2.current, 'L2')"
    },
    {
     "target": "alias(deye.ac.ups.l3.current, 'L3')"
    }
   ]
  },
  { "title": "PV MPP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "MPP: Leistung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "target": "alias(deye.dc.pv1.power, 'String 1 - West')"
    },
    {
     "target": "alias(deye.dc.pv2.power, 'String 2 - Ost')"
    }
   ]
  },
  {
   "title": "MPP: Spannung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "target": "alias(deye.dc.pv1.voltage, 'String 1 - West')"
    },
    {
     "target": "alias(deye.dc.pv2.voltage, 'String 2 - Ost')"
    }
   ]
  },
  {
   "title": "MPP: Strom",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "target": "alias(deye.dc.pv1.current, 'String 1 - West')"
    },
    {
     "target": "alias(deye.dc.pv2.current, 'String 2 - Ost')"
    }
   ]
  }
 ]
}